defaults:
    region: 'eu-west-1'

services:
    kinesis:
        version: '2013-12-02'

        producer:
            mocks:
                path: resources/mocks/kinesis/
      
    api_gateway:
        version: '2015-07-09'
    
        producer:
            mocks:
                path: resources/mocks/api-gateway/
            
    sts:
        version: '2011-06-15'
        endpoint: 'https://sts.eu-west-1.amazonaws.com'
        
    iam:
        version: '2010-05-08'